1. What are the similarities and differences between pandas and numpy?   Include some type of example with code.


Pandas and NumPy are both Python libraries for efficient data handling, supporting fast operations and functions like mean and sum, making them essential for data analysis.

NumPy focuses on numerical data using the ndarray (n-dimensional array) structure, which works best with consistent data types across the array. Pandas, on the other hand, provides Series (single-column labeled arrays) and DataFrames (two-dimensional labeled tables), which allow for easier handling of mixed data types. The labeled structure of Series and DataFrames makes data manipulation in Pandas more intuitive and readable compared to the position-based indexing in NumPy’s ndarray.

In [14]:
import numpy as np
import pandas as pd

# Creating a 3D array with numbers in the 10s for readability
num_2d_arr = np.array([
  [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("3D NumPy Array:\n", num_2d_arr)

# Summing across the first axis 
sum_cols = np.sum(num_2d_arr, axis=0)
print("Sum for each column in the 3D array:\n", sum_cols)


###################### pandas df example
fk_got_data = {
    'House': ['Stark', 'Lannister', 'Baratheon', 'Tully', 'Greyjoy', 'Arryn', 'Martell'],
    'Troops_Before': [50000, 70000, 40000, 30000, 25000, 20000, 45000],
    'Troops_After': [30000, 50000, 10000, 15000, 20000, 15000, 40000]
}

# Creating the DataFrame
houses_of_westeros = pd.DataFrame(fk_got_data)
print("Houses of Westeros Troop Counts:\n", houses_of_westeros)


3D NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Sum for each column in the 3D array:
 [120 150 180]
Houses of Westeros Troop Counts:
        House  Troops_Before  Troops_After
0      Stark          50000         30000
1  Lannister          70000         50000
2  Baratheon          40000         10000
3      Tully          30000         15000
4    Greyjoy          25000         20000
5      Arryn          20000         15000
6    Martell          45000         40000


2. What is the ndarray in numPy?



The "n" in ndarray means it can have multiple dimensions:

A 1D array is essentially a straightforward list of numbers.
A 2D array resembles a table or matrix with rows and columns.
A 3D array introduces layers, like stacking several 2D tables on top of each other.

3. Create a 1D array of numbers from 0 to 9 
Desired Output: 
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
decimalnums = np.array([0,1,2,3,4,5,6,7,8,9])
print(decimalnums)

[0 1 2 3 4 5 6 7 8 9]


4. Extract all odd numbers from array1 
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [16]:
decimalnums = decimalnums[decimalnums % 2 != 0]
print(" Odd Numbers:", decimalnums)

 Odd Numbers: [1 3 5 7 9]


5. Get the common items between a and  b  
#input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Desired Output:

array([2, 4])


In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

ab = np.intersect1d(a, b)
print("Common elements:", ab)

Common elements: [2 4]


6. From array a remove all items present in array  b 
#Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

#Desired Output:

array([1,2,3,4])


In [18]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a,b)
print(a)

[1 2 3 4]


7. Find out if iris has any missing values. 
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [19]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

print(iris[:5])
## lets see if any cell in iris returns a non number
has_nan = np.isnan(iris).any()
print("True Or False,\nDoes the Iris dataset contain any NaN values?\n",has_nan)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
True Or False,
Does the Iris dataset contain any NaN values?
 False
